In [149]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

In [150]:
dataset = pd.read_csv("Data_before.csv", na_values=['None', ' nan'])

In [151]:
dataset.columns

Index(['time', 'solarRadiation', 'uvHigh', 'winddirAvg', 'humidityHigh',
       'humidityLow', 'humidityAvg', 'qcStatus', 'tempHigh', 'tempLow',
       'tempAvg', 'windspeedHigh', 'windgustLow', 'windspeedAvg', 'dewptHigh',
       'dewptLow', 'dewptAvg', 'windchillHigh', 'windchillAvg',
       'heatindexHigh', 'heatindexLow', 'heatindexAvg', 'pressureMax',
       'pressureMin', 'pressureTrend', 'precipRate', 'precipTotal', 'power'],
      dtype='object')

In [152]:
dataset.head()

,time,solarRadiation,uvHigh,winddirAvg,humidityHigh,humidityLow,humidityAvg,qcStatus,tempHigh,tempLow,...,windchillAvg,heatindexHigh,heatindexLow,heatindexAvg,pressureMax,pressureMin,pressureTrend,precipRate,precipTotal,power
0,14:20:00,677.62,7.0,182.0,24.0,24.0,24.0,-1,66.0,66.0,...,66.0,66.0,66.0,66.0,30.06,30.06,NaN,0.0,0.0,-422.322232
1,14:29:00,627.70,7.0,195.0,24.0,24.0,24.0,-1,65.0,65.0,...,65.0,65.0,65.0,65.0,30.06,30.05,0.60,0.0,0.0,-403.168317
2,14:34:00,617.31,7.0,129.0,24.0,23.0,23.0,-1,68.0,66.0,...,67.0,68.0,66.0,67.0,30.06,30.05,-0.15,0.0,0.0,NaN
3,14:39:00,608.13,6.0,108.0,24.0,23.0,23.0,-1,68.0,67.0,...,67.0,68.0,67.0,67.0,30.06,30.05,0.00,0.0,0.0,-389.270927
4,14:44:00,582.57,6.0,87.0,25.0,24.0,24.0,-1,67.0,66.0,...,66.0,67.0,66.0,66.0,30.06,30.05,-0.15,0.0,0.0,-379.477948

In [153]:
print('Before removing the nan', dataset.shape)

Before removing the nan (6264, 28)

In [154]:
dataset = dataset[dataset['power'].notna()]

print('After removing the nan', dataset.shape)

After removing the nan (3465, 28)

In [161]:
print('the percentage of the zeros in precipRate column' , dataset['precipRate'].isin([0]).sum() / dataset['precipRate'].shape[0])
print('the percentage of the zeros in precipTotal column' , dataset['precipTotal'].isin([0]).sum() / dataset['precipTotal'].shape[0])

the percentage of the zeros in precipRate column 0.9595959595959596
the percentage of the zeros in precipTotal column 0.8225108225108225

In [162]:
#Dropping 'precipRate' and 'precipTotal' because it is mostly zero

dataset.drop(['precipRate','precipTotal'], axis=1, inplace=True)

dataset.head()

,time,solarRadiation,uvHigh,winddirAvg,humidityHigh,humidityLow,humidityAvg,qcStatus,tempHigh,tempLow,...,dewptAvg,windchillHigh,windchillAvg,heatindexHigh,heatindexLow,heatindexAvg,pressureMax,pressureMin,pressureTrend,power
0,14:20:00,677.62,7.0,182.0,24.0,24.0,24.0,-1,66.0,66.0,...,28.0,66.0,66.0,66.0,66.0,66.0,30.06,30.06,NaN,-422.322232
1,14:29:00,627.70,7.0,195.0,24.0,24.0,24.0,-1,65.0,65.0,...,28.0,65.0,65.0,65.0,65.0,65.0,30.06,30.05,0.60,-403.168317
3,14:39:00,608.13,6.0,108.0,24.0,23.0,23.0,-1,68.0,67.0,...,29.0,68.0,67.0,68.0,67.0,67.0,30.06,30.05,0.00,-389.270927
4,14:44:00,582.57,6.0,87.0,25.0,24.0,24.0,-1,67.0,66.0,...,29.0,67.0,66.0,67.0,66.0,66.0,30.06,30.05,-0.15,-379.477948
5,14:49:00,571.67,6.0,38.0,24.0,24.0,24.0,-1,66.0,66.0,...,28.0,66.0,66.0,66.0,66.0,66.0,30.05,30.04,-0.15,-370.189019

In [163]:
missing_columns = [col for col in dataset.columns if dataset[col].isna().any()]
missing_columns

['solarRadiation',
 'uvHigh',
 'winddirAvg',
 'humidityHigh',
 'humidityLow',
 'humidityAvg',
 'tempHigh',
 'tempLow',
 'tempAvg',
 'windspeedHigh',
 'windgustLow',
 'windspeedAvg',
 'dewptHigh',
 'dewptLow',
 'dewptAvg',
 'windchillHigh',
 'windchillAvg',
 'heatindexHigh',
 'heatindexLow',
 'heatindexAvg',
 'pressureTrend']

In [164]:
smp = SimpleImputer(missing_values=np.nan, strategy='mean')
dataset[missing_columns] = smp.fit_transform(dataset[missing_columns])

In [165]:
print('Total number of missing values ', dataset.isna().any().sum())
print('The final shape of the dataset ', dataset.shape)

Total number of missing values  0
The final shape of the dataset  (3465, 26)

In [166]:
dataset.head()

,time,solarRadiation,uvHigh,winddirAvg,humidityHigh,humidityLow,humidityAvg,qcStatus,tempHigh,tempLow,...,dewptAvg,windchillHigh,windchillAvg,heatindexHigh,heatindexLow,heatindexAvg,pressureMax,pressureMin,pressureTrend,power
0,14:20:00,677.62,7.0,182.0,24.0,24.0,24.0,-1,66.0,66.0,...,28.0,66.0,66.0,66.0,66.0,66.0,30.06,30.06,0.001357,-422.322232
1,14:29:00,627.70,7.0,195.0,24.0,24.0,24.0,-1,65.0,65.0,...,28.0,65.0,65.0,65.0,65.0,65.0,30.06,30.05,0.600000,-403.168317
3,14:39:00,608.13,6.0,108.0,24.0,23.0,23.0,-1,68.0,67.0,...,29.0,68.0,67.0,68.0,67.0,67.0,30.06,30.05,0.000000,-389.270927
4,14:44:00,582.57,6.0,87.0,25.0,24.0,24.0,-1,67.0,66.0,...,29.0,67.0,66.0,67.0,66.0,66.0,30.06,30.05,-0.150000,-379.477948
5,14:49:00,571.67,6.0,38.0,24.0,24.0,24.0,-1,66.0,66.0,...,28.0,66.0,66.0,66.0,66.0,66.0,30.05,30.04,-0.150000,-370.189019

In [168]:
dataset.to_csv("cleanedData.csv", header = True, index = False)